const db = require('../database/db');
const { scrapeWebsite } = require('../services/scraperService');
const { analyzeInstallerFile } = require('../services/fileAnalyzerService');
const { fetchSoftwareImages } = require('../services/imageService');
const { generateSoftwareMetadata } = require('../services/aiService');

/**
 * Controller to handle AI Software Publisher generation.
 */
async function generateSoftwareDetails(req, res) {
  try {
    const softwareName = (req.body.software_name || req.body.name || '').trim();
    const websiteUrl = (req.body.website_url || req.body.url || '').trim();

    // Check if an installer file was uploaded during AI generation request
    let uploadedFile = null;
    if (req.files && req.files['installer_file'] && req.files['installer_file'][0]) {
      uploadedFile = req.files['installer_file'][0];
    } else if (req.file) {
      uploadedFile = req.file;
    }

    if (!softwareName && !websiteUrl && !uploadedFile) {
      return res.status(400).json({
        success: false,
        error: 'Please provide a Software Name, Official Website URL, or Upload an Installer file.'
      });
    }

    // 1. Analyze installer file if provided
    let fileMeta = { hasFile: false };
    let savedFilePath = '';
    if (uploadedFile) {
      savedFilePath = uploadedFile.filename;
      fileMeta = analyzeInstallerFile(uploadedFile.path, uploadedFile.originalname);
    }

    // 2. Scrape official website if URL provided
    let scrapedMeta = {};
    if (websiteUrl) {
      scrapedMeta = await scrapeWebsite(websiteUrl, 15000);
    }

    // Get site configuration from app locals or req
    const config = (req.app && req.app.locals && req.app.locals.getConfig) ? req.app.locals.getConfig() : {};

    // 3. Generate structured metadata using AI API or heuristic generator
    const generatedData = await generateSoftwareMetadata({
      softwareName,
      websiteUrl,
      fileMeta,
      scrapedMeta,
      config
    });

    // 4. Automatically fetch / download official logo, icon, and screenshots
    const imageMeta = await fetchSoftwareImages(generatedData.name || softwareName, websiteUrl, scrapedMeta);

    // 5. Match generated category to existing category in database
    const categories = await db.all('SELECT * FROM categories ORDER BY name ASC');
    let matchedCategoryId = null;

    if (categories && categories.length > 0) {
      const targetCat = (generatedData.category || '').toLowerCase();
      const match = categories.find(c => c.name.toLowerCase() === targetCat || targetCat.includes(c.name.toLowerCase()));
      matchedCategoryId = match ? match.id : categories[0].id; // Fallback to first category
    }

    // Return structured response
    res.json({
      success: true,
      message: 'Software details successfully generated by AI Publisher!',
      data: {
        ...generatedData,
        category_id: matchedCategoryId,
        icon_image: imageMeta.icon_image || '',
        screenshots: imageMeta.screenshots || '[]',
        file_path: savedFilePath || '',
        file_size: generatedData.size || fileMeta.fileSizeFormatted || '0 MB'
      }
    });

  } catch (err) {
    console.error('[AIController] Error generating software details:', err);
    res.status(500).json({
      success: false,
      error: err.message || 'An error occurred while generating software details with AI.'
    });
  }
}

module.exports = {
  generateSoftwareDetails
};
