const bcrypt = require('bcryptjs');
const path = require('path');
const fs = require('fs');

async function runSeed() {
  console.log('Starting database seeding...');

  // Make sure we load the db module (which initializes the schema)
  const db = require('../database/db');

  // Wait a moment for schema execution to complete
  await new Promise(resolve => setTimeout(resolve, 500));

  // 1. Create Default Admin User (username: hemanth, password: bhemanth)
  const adminUsername = 'hemanth';
  const adminPassword = 'bhemanth';

  // Clear any existing admin users to update to the new credentials
  await db.run('DELETE FROM admin_users');

  const salt = bcrypt.genSaltSync(10);
  const hash = bcrypt.hashSync(adminPassword, salt);
  await db.run('INSERT INTO admin_users (username, password_hash) VALUES (?, ?)', [adminUsername, hash]);
  console.log(`Default admin user created: Username: "${adminUsername}", Password: "${adminPassword}"`);

  // 2. Create Categories
  const categories = [
    { name: 'Utilities', slug: 'utilities' },
    { name: 'Browsers', slug: 'browsers' },
    { name: 'Security', slug: 'security' },
    { name: 'Office', slug: 'office' },
    { name: 'Multimedia', slug: 'multimedia' },
    { name: 'Development', slug: 'development' }
  ];

  for (const cat of categories) {
    const existing = await db.get('SELECT * FROM categories WHERE name = ?', [cat.name]);
    if (!existing) {
      await db.run('INSERT INTO categories (name, slug) VALUES (?, ?)', [cat.name, cat.slug]);
      console.log(`Created category: ${cat.name}`);
    }
  }

  // Get Category IDs
  const catRows = await db.all('SELECT * FROM categories');
  const catMap = {};
  catRows.forEach(row => {
    catMap[row.name] = row.id;
  });

  // 3. Create Sample Software Listings & Dummy Files
  const storageDir = path.resolve(__dirname, '../storage');
  const softwareDir = path.join(storageDir, 'software');
  const imagesDir = path.join(storageDir, 'images');

  // Helper to create a mock image (a clean SVG/text or just a small dummy file)
  // For the UI, we can use SVG file creation or base64. Let's write standard PNG/SVG dummy files.
  // Actually, let's create simple SVG files with .png extensions or simple text files since browsers can display them
  // or write a tiny actual image, or let EJS render custom styles. Writing a clean SVG is great!
  const createMockIcon = (name, bgColor, text) => {
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
      <rect width="100" height="100" rx="15" fill="${bgColor}"/>
      <text x="50%" y="55%" dominant-baseline="middle" text-anchor="middle" font-family="Arial, sans-serif" font-size="36" font-weight="bold" fill="#ffffff">${text}</text>
    </svg>`;
    const filePath = path.join(imagesDir, name);
    fs.writeFileSync(filePath, svg);
  };

  const createDummySoftwareFile = (filename, sizeMb) => {
    const filePath = path.join(softwareDir, filename);
    const content = `Windows Installer binary placeholder for ${filename}.\nTarget size: ${sizeMb} MB.\nThis is a fully-working download link generated by Software Hub.`;
    fs.writeFileSync(filePath, content);
  };

  // Define sample software list
  const softwareList = [
    {
      name: 'Google Chrome',
      category: 'Browsers',
      short_description: 'Fast, secure, and easy-to-use browser built for the modern web.',
      full_description: 'Google Chrome is a fast, simple, and secure web browser, built for the modern web. It runs web applications and pages with lightning speed, features a clean interface, and integrates Google Account synchronization across all your devices.',
      version: '124.0.6367.61',
      size: '95 MB',
      icon_image: 'chrome-icon.svg',
      file_path: 'chrome-installer.exe',
      is_featured: 1,
      is_new: 0,
      bgColor: '#4285F4',
      text: 'GC'
    },
    {
      name: 'VLC Media Player',
      category: 'Multimedia',
      short_description: 'The open-source multi-platform multimedia player that plays almost everything.',
      full_description: 'VLC is a free and open-source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols. Features highly customizable skins and extension support.',
      version: '3.0.20',
      size: '42 MB',
      icon_image: 'vlc-icon.svg',
      file_path: 'vlc-installer.exe',
      is_featured: 1,
      is_new: 1,
      bgColor: '#FF8800',
      text: 'VLC'
    },
    {
      name: '7-Zip',
      category: 'Utilities',
      short_description: 'High compression ratio file archiver utility.',
      full_description: '7-Zip is a file archiver with a high compression ratio. It supports 7z, ZIP, GZIP, BZIP2 and TAR formats, and features a clean shell integration, strong AES-256 encryption in 7z and ZIP formats, and a powerful Command Line version.',
      version: '24.05',
      size: '2.5 MB',
      icon_image: '7zip-icon.svg',
      file_path: '7zip-installer.exe',
      is_featured: 0,
      is_new: 1,
      bgColor: '#2E7D32',
      text: '7Z'
    },
    {
      name: 'VS Code',
      category: 'Development',
      short_description: 'Code editing. Redefined. Free and open source.',
      full_description: 'Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop. It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages and runtimes.',
      version: '1.89.1',
      size: '88 MB',
      icon_image: 'vscode-icon.svg',
      file_path: 'vscode-installer.exe',
      is_featured: 1,
      is_new: 0,
      bgColor: '#007ACC',
      text: 'VS'
    },
    {
      name: 'LibreOffice',
      category: 'Office',
      short_description: 'The free, powerful, and open-source office productivity suite.',
      full_description: 'LibreOffice is a powerful and free office suite, a successor to OpenOffice.org. Its clean interface and feature-rich tools help you unleash your creativity and organize your productivity. Includes Writer (word processing), Calc (spreadsheets), and Impress (presentations).',
      version: '24.2.3',
      size: '340 MB',
      icon_image: 'libreoffice-icon.svg',
      file_path: 'libreoffice-installer.exe',
      is_featured: 0,
      is_new: 0,
      bgColor: '#117E11',
      text: 'LO'
    },
    {
      name: 'Malwarebytes',
      category: 'Security',
      short_description: 'Industry-leading anti-malware and security protection.',
      full_description: 'Malwarebytes protects you against malware, ransomware, malicious websites, and other advanced threats. It cleans infected devices, monitors your systems in real-time, and safeguards your privacy with intuitive dashboard settings.',
      version: '4.6.12',
      size: '180 MB',
      icon_image: 'malwarebytes-icon.svg',
      file_path: 'malwarebytes-installer.exe',
      is_featured: 0,
      is_new: 1,
      bgColor: '#0054FF',
      text: 'MB'
    }
  ];

  for (const sw of softwareList) {
    const existing = await db.get('SELECT * FROM software WHERE name = ?', [sw.name]);
    if (!existing) {
      // Create mock icon SVG
      createMockIcon(sw.icon_image, sw.bgColor, sw.text);
      // Create mock download binary
      createDummySoftwareFile(sw.file_path, parseFloat(sw.size));

      const categoryId = catMap[sw.category];
      await db.run(
        `INSERT INTO software 
         (name, category_id, short_description, full_description, version, size, icon_image, file_path, is_featured, is_new) 
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          sw.name,
          categoryId,
          sw.short_description,
          sw.full_description,
          sw.version,
          sw.size,
          sw.icon_image,
          sw.file_path,
          sw.is_featured,
          sw.is_new
        ]
      );
      console.log(`Created software listing: ${sw.name}`);
    }
  }

  console.log('Seeding finished successfully.');
  await db.close();
}

runSeed().catch(err => {
  console.error('Seeding failed:', err);
});
